### ISSUE TITLE
non-determinism on tf.keras.layers.UpSampling2D(..., interpolation='nearest')

### ISSUE THREAD

**Issue by emiliocoutinho** [NVIDIA/framework-determinism#24]
I believe there is a source of non-determinism on tf.keras.layers.UpSampling2D with interpolation='nearest', as you suggest on [Other Possible GPU-Specific Sources of Non-Determinism](https://github.com/NVIDIA/framework-determinism#other-possible-gpu-specific-sources-of-non-determinism). 

In my case, I was building an auto-encoder, and on the decoder part, there were some procedures that I was not satisfied with and I was just waiting for the right time to change them. Turns out that this part was responsible for the non-deterministic behavior and as in #12, I replaced:
```
tf.keras.layers.UpSampling2D(..., interpolation='nearest')
ReflectionPadding2D()  # that is nothing more than a tf.pad(..., mode='REFLECT')
tf.keras.layers.Conv2D(..., padding='valid')
```
by:
```
tf.keras.layers.Conv2DTranspose(...,padding='same')
```

and now I have reproducible results on GPU and on CPU.

Thanks for the effort in building this package, it is very useful.

Best Regards.

**Comment by duncanriach** [comment]
Awesome work. Thanks Emilio. I'm going to move this source up into the confirmed list and review its priority relative to other ops, given that it's probably going to be a similar solution to that for bilinear filtering (referencing TF [PR 39243](https://github.com/tensorflow/tensorflow/pull/39243)). Thanks also for reporting the work-around.

**Comment by duncanriach** [comment]
With [this commit](https://github.com/NVIDIA/framework-determinism/commit/921cbc32aa6c0c27698000650ec5560c0156c855), I have updated README.md to reflect all of this. I have also added fixing nearest neighbor resizing to my to-do list. This feature addition is in the pipeline to get added to TensorFlow. I'm going to close this issue now.

**Comment by duncanriach** [comment]
Closing.
